modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="greenlantern"
version="1.0.0"
displayName="Green Lantern Power Ring"
description='''
El Anillo de Poder de Linterna Verde (inspirado en Justice League Heroes).
Vuelo, rayo de energia, escudo y construcciones de energia verde.
'''

[[dependencies.greenlantern]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.greenlantern]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
